export const site = {
  name: "Javier Carrillo Milla",
  title: "Freelance Software Engineer",
  email: "stringparser@gmail.com",
  github: "https://github.com/stringparser",
  twitter: "https://twitter.com/stringparser",
  cvPdf:
    "https://github.com/stringparser/cv/raw/main/dist/cv.pdf",
  url: "https://stringparser.github.io",
  keywords: [
    "software",
    "engineer",
    "bash",
    "zsh",
    "git",
    "docker",
    "kubernetes",
    "nodejs",
    "npm",
    "yarn",
    "lerna",
    "expressjs",
    "koa",
    "mocha",
    "jest",
    "tape",
    "mongodb",
    "mysql",
    "rabbitmq",
    "kafka",
    "material-ui",
    "nextjs",
    "jss",
    "bootstrap",
    "playframework",
    "browserify",
    "webpack",
    "gulp",
    "grunt",
    "react.js",
    "react native",
    "zustand",
    "redux",
    "rxjs",
    "graphql",
  ],
} as const;

export const navLinks = [
  { href: "/about", label: "about" },
  { href: `mailto:${site.email}`, label: "contact", external: true },
] as const;
