/** Declaration file generated by dts-gen */

declare module 'txtgen' {
  export function sentence(): string;
  export function article(len?: number): string;
  export function paragraph(len?: number): string;
  export function addNouns(ls: string[]): string;
  export function addTemplates(ls: string[]): string;
  export function addAdjectives(ls: string[]): string;
}

